# Generated by Django 5.2.9 on 2026-01-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن تماس'),
        ),
        migrations.AddField(
            model_name='user',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس فروشگاه/محل کار'),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فروشگاه/برند'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ادمین'), ('CUSTOMER', 'مشتری'), ('SELLER', 'فروشنده')], default='CUSTOMER', max_length=50, verbose_name='نقش'),
        ),
    ]
