# Generated by Django 5.2.9 on 2026-01-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_address',
        ),
    ]
