# Generated by Django 5.2.9 on 2026-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس فروشگاه/محل کار'),
        ),
    ]
