# Generated by Django 5.2.9 on 2026-01-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_store_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_address',
        ),
    ]
