# Generated by Django 5.2.9 on 2026-02-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_supportsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportSubscription',
        ),
    ]
