# Generated by Django 5.2.9 on 2025-12-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_style_product_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
